
server:
      port: 443
      #访问地址
      address: 0.0.0.0
      # #开启https,配置跟证书对应
      ssl:
            key-store: classpath:auth_server.keystore
            key-store-password: auth_server
            key-alias: auth_server
            key-password: auth_server
            key-store-type: JKS
            enabled-protocols: TLSv1.2, TLSv1.3
            enabled: true
            #是否需要进行认证
            client-auth: need
            protocol: TLS # 默认
            trust-store: classpath:auth_server.keystore
            trust-store-password: auth_server
            trust-store-type: JKS




spring:
devtools:
restart:
enabled: false